/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_net_conf_EnclaveInterface */

#ifndef _Included_com_example_net_conf_EnclaveInterface.h
#define _Included_com_example_net_conf_EnclaveInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_net_conf_EnclaveInterface
 * Method:    callEnclave
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_net_conf_EnclaveInterface_callEnclave
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
